openapi: 3.0.0
info:
  title: Chat API
  description: |
    The SuperFocus API is organized around REST. It allows you to interact with a chatbot with access to corpuses of documents you have provided to us. Both unary completions and streaming are supported. Please authenticate your requests with an API key, which you will receive from us.
  version: 1.0.0

servers:
  - url: https://rust-api-backend-33eo7kltwq-uw.a.run.app

paths:
  /v1/chat/completions:
    post:
      summary: Process a chat completion request
      description: This endpoint allows you to submit a chat history, and receive the next message from the chatbot.
      operationId: chatCompletions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalApiRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalApiResponse'
      security:
        - ApiKeyAuth: []

  /v1/chat/stream-completions:
    post:
      summary: Process a streaming chat completion request
      description: Submit a chat history to this endpoint, and get back a stream of completions via Server-Sent Events that represent the next message. This is useful when latency is important for the user's experiance.
      operationId: streamChatCompletions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalApiRequest'
      responses:
        '200':
          description: Successful response
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuFoCompletionStreamChunk'
      security:
        - ApiKeyAuth: []

components:
  schemas:
    ExternalApiRequest:
      type: object
      properties:
        corpus_name:
          type: string
          description: The name of the corpus of data that you want to query. SuperFocus will provide this value to you.
        messages:
          type: array
          items:
            $ref: '#/components/schemas/CgptMsg'
          description: A list of messages comprising the conversation so far, from oldest to newest. The last entry in the list should be the new message from the user.
        session_id:
          type: string
          nullable: true
          description: This allows us to keep track of your session internally, for debugging purposes. You can set this to any string you want, and it is not necessary to include it in your requests.

    ExternalApiResponse:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/CgptMsg'
        sources:
          type: array
          items:
            $ref: '#/components/schemas/ExternalApiSource'
          description: A list of sources that the chatbot used to generate this completion.

    ExternalApiSource:
      type: object
      description: A source that the chatbot is using to generate this completion. Typically, either raw text, or a URL to a PDF.
      properties:
        title:
          type: string
          description: The title of the source.
        url:
          type: string
          nullable: true
          description: The URL of the source, if there is one.
        content:
          type: string
          description: The text of the source, if there is one.

    CgptMsg:
      type: object
      properties:
        role:
          type: string
          description: The role of the speaker of this message. This should be either "user" or "assistant".
        content:
          type: string
          description: The content of the message.
        name:
          type: string
          nullable: true
          description: The name associated with the message, if applicable.
        function_call:
          type: string
          nullable: true
          description: A specific function call related to the message, if applicable.

    SuFoCompletionStreamChunk:
      type: object
      properties:
        completion:
          type: string
          description: The next chunk of text from the chatbot.
        role:
          type: string
          nullable: true
          description: Either "user" or "assistant" or not set. For example, the first chunk might be "assistant", and then every message after that is assumed to still be from the assistant.
        stop_reason:
          type: string
          nullable: true
          description: The reason why the chatbot decided to stop generating more text.
        do_overwrite:
          type: boolean
          description: If true, you should overwrite the current message in the chat history with this. Otherwise, append the chunk to the current message.
        sources:
          type: array
          items:
            $ref: '#/components/schemas/ExternalApiSource'
          description: A list of sources that the chatbot is using to generate this completion. Each source is only sent once.


securitySchemes:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-auth-apikey
    description: The SuperFocus API uses API keys to authenticate requests. We will send you an API key when you are ready to interact with the SuperFocus API. All API requests should include your API key in an `x-auth-apikey` HTTP header.
